services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    ports:
      - '5000:5000'
    hostname: edcast.mock
    networks:
      - devstack-nutmegmaster_default

networks:
  devstack-nutmegmaster_default:
    external: true
